Solution to task on python exceptions
